### ISSUE TITLE
Add __str__ methods to models

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#11]
Now, a dropdown list of e.g. Places shows 'Place object' and the UUID. Adding a __str__ method will at least show a default value.

**Comment by dennis-bor** [comment]
Added __str__ to most models in [this](https://github.com/tsg-humlab/shewrote/commit/5c8673c66c8c39ce27c95f0fbbce715b4ffc74cd) commit.

**Comment by dennis-bor** [comment]
The Edition model doesn't have an obvious attribute to use for the /__str__/ method. Should we include a title field for Editions @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
> The Edition model doesn't have an obvious attribute to use for the **str** method. Should we include a title field for Editions @vanlummelhuizen ?

I don't think we should introduce thing solely for this purpose. I think we can leave it for now and fix it later when things are more clear.
