### ISSUE TITLE
Create explicit m2m linking table for persons related to field

### ISSUE THREAD

**Issue by dennis-bor** [tsg-humlab/shewrote#18]

**Comment by vanlummelhuizen** [comment]
This Stackoverflow page may come in handy: https://stackoverflow.com/questions/33257530/how-to-add-through-option-to-existing-manytomanyfield-with-migrations-and-data-i

**Comment by vanlummelhuizen** [comment]
May be this one is even better: https://docs.djangoproject.com/en/4.2/howto/writing-migrations/#changing-a-manytomanyfield-to-use-a-through-model

**Comment by vanlummelhuizen** [comment]
The code in https://github.com/tsg-humlab/shewrote/commit/403e2de459aa56658355c4291c33cc7e5ee9b247 seems to do the trick. I am only in doubt about the `related_name` arguments in the `from_person` and `to_person` fields of `PersonPersonRelation`. @dennis-bor could you shine your light on this?

**Comment by vanlummelhuizen** [comment]
See #29

**Comment by vanlummelhuizen** [comment]
@dennis-bor @ACNMontoya 

Er zijn enkele wijzigingen met betrekking to *related_to*. In de admin is er een nieuw tabblad: *Parents*, waar alleen *Mother* en *Father* op staan. Op het tabblad *Relations* werkt het toevoegen van *related_to*-personen ietsje anders: in plaats van meerdere personen in een enkel veld selecteren, moet je nu per veld een persoon selecteren en bij meerdere personen op *Add another Relation* klikken.

Dit is nodig om ook een relation_type-veld te kunnen toevoegen op een later moment. Zie #32 

**NB. Dit is nu alleen nog op de test-server. Dus ik hoor graag of het in orde is en naar de live-server kan.**

**Comment by ACNMontoya** [comment]
Dit lijkt mij prima.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 28 augustus 2024 11:29
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Create explicit m2m linking table for persons related to field (Issue #18)


@dennis-bor<https://github.com/dennis-bor> @ACNMontoya<https://github.com/ACNMontoya>

Er zijn enkele wijzigingen met betrekking to related_to. In de admin is er een nieuw tabblad: Parents, waar alleen Mother en Father op staan. Op het tabblad Relations werkt het toevoegen van related_to-personen ietsje anders: in plaats van meerdere personen in een enkel veld selecteren, moet je nu per veld een persoon selecteren en bij meerdere personen op Add another Relation klikken.

Dit is nodig om ook een relation_type-veld te kunnen toevoegen op een later moment. Zie #32<https://github.com/tsg-humlab/shewrote/issues/32>

NB. Dit is nu alleen nog op de test-server. Dus ik hoor graag of het in orde is en naar de live-server kan.

**Comment by vanlummelhuizen** [comment]
Dit staat nu ook op de live server, dus ik sluit dit issue.
