### ISSUE TITLE
Marriages setup

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#23]
@ACNMontoya @dennis-bor 

Just now I added a Marriage tab to the admin page for changing a Person on the test server (e.g. https://test.shewrote.rich.ru.nl/admin/shewrote/person/e98cf5f8-9a9b-4c5e-992c-b4d36a7eb50c/change/#marriages).

When creating a Marriage (click on '+ Add another Marriage') there are actually two Marriage objects created, one for each direction. Updating and deleting one direction should also update or delete the other direction. 

**Note that this setup does not account for the occasion that a couple are married multiple times.** See also our mail correspondence on april 11, 2024 with subject *Shewrote: meerdere huwelijken tussen twee mensen?*.

Let me know what you think.

**Comment by ACNMontoya** [comment]
Beste Micha,

Dank hiervoor, maar de data over marriages uit de vorige versie van de database staat nog niet in SHEWROTE, kan dat erbij?

Hartelijks,
Alicia

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: maandag 8 juli 2024 14:25
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Marriages setup (Issue #23)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Assigned #23<https://github.com/tsg-humlab/shewrote/issues/23> to @ACNMontoya<https://github.com/ACNMontoya>.

**Comment by vanlummelhuizen** [comment]
Ja, daar ga ik naar kijken.

**Comment by vanlummelhuizen** [comment]
Ik kan in de data van Womenwriters geen zaken vinden die een marriage (= Person-Person-relatie) aangeven. Alleen 'Marital status' en Spouse bij Temporary data (zie bv https://womenwriters.rich.ru.nl/womenwriters/vre/persons/0cba6668-ed04-4df6-8021-7e389ad12b9a/personal-situation). Met alleen een spouse-naam, dus geen ID, kan ik geen script maken om marriage-data te importeren. Kijk ik ergens overheen?

**Comment by ACNMontoya** [comment]
Aha, dat zie ik nu. Als het niet mogelijk is een script te maken om die data te importeren uit 'temporary data', dan zullen we dat handmatig moeten overzetten. Ik zie wel dat 'spouse' een aparte veld is in de 1e versie van de database, zie bijv. http://neww.huygens.knaw.nl/authors/show/7, help dat?

Hartelijks,
Alicia

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: maandag 8 juli 2024 15:33
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Marriages setup (Issue #23)


Ik kan in de data van Womenwriters geen zaken vinden die een marriage (= Person-Person-relatie) aangeven. Alleen 'Marital status' en Spouse bij Temporary data (zie bv https://womenwriters.rich.ru.nl/womenwriters/vre/persons/0cba6668-ed04-4df6-8021-7e389ad12b9a/personal-situation). Met alleen een spouse-naam, dus geen ID, kan ik geen script maken om marriage-data te importeren. Kijk ik ergens overheen?

**Comment by vanlummelhuizen** [comment]
> Ik zie wel dat 'spouse' een aparte veld is in de 1e versie van de database, zie bijv. http://neww.huygens.knaw.nl/authors/show/7, help dat?

Het lijkt erop dat dat ook alleen een naam is en geen ID ofzo. We moeten misschien ook even de dump van het Huygens afwachten.

Ik kan overigens altijd met de tekst in Spouse van de Temporary data een nieuwe Person aanmaken. Die is dat verder wel leeg en een eventuele Marriage met een bestaande Person object wordt dan niet gemaakt.

**Comment by vanlummelhuizen** [comment]
Ik heb hier opnieuw naar gekeken en daarbij de datadump van de eerste versie van Womenwriters meegenomen. Ook die laatste heeft slechts een tekst-veld met de naam van de *spouse*.  

Een kleine steekproef laat zien dat de spouse-namen niet naar een bestaande author/person-object verwijzen. Met andere woorden, een Person-Person-relatie zit er sowieso niet in. 

Ik kan natuurlijk de spouse-naam gebruiken om daar een nieuwe -verder lege- Person-object van te maken. Het is dat aan editors om de info van die Person-objecten verder aan te vullen, indien nodig.

**Comment by ACNMontoya** [comment]
Je bedoelt dat wij dan zelf een Person-Person relatie moeten aanmaken? Dat wordt wel een enorme klus.

Bij wat testjes gisteren merkten we al dat er erg veel informatie verloren is gegaan door het verdwijnen van die spouse names (die gelinkt zijn aan sommige alternative names). Zo is Geertruida Bosboom-Toussaint ineens onvindbaar geworden (onder die naam, waaronder ze gewoon bekend staat) in SHEWROTE. Vergelijk de oude en nieuwe versies van de database:

[cid:f9fcace1-9825-4c2c-a5a7-14a1e4fd4097]

[cid:13b2eb50-0457-4fd7-968f-64240a653fc5]
---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: dinsdag 20 augustus 2024 11:47
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Marriages setup (Issue #23)


Ik heb hier opnieuw naar gekeken en daarbij de datadump van de eerste versie van Womenwriters meegenomen. Ook die laatste heeft slechts een tekst-veld met de naam van de spouse.

Een kleine steekproef laat zien dat de spouse-namen niet naar een bestaande author/person-object verwijzen. Met andere woorden, een Person-Person-relatie zit er sowieso niet in.

Ik kan natuurlijk de spouse-naam gebruiken om daar een nieuwe -verder lege- Person-object van te maken. Het is dat aan editors om de info van die Person-objecten verder aan te vullen, indien nodig.

**Comment by vanlummelhuizen** [comment]
De Person-Person-relatie kan ik wel maken, maar die bevat dan niet meer dan een short_name, gewoonweg omdat er niet meer in WomenWriters zit dan dat.

---

Ik heb even gekeken of ik Geertruida Bosboom-Toussaint kon vinden en volgens mij is dit haar: https://test.shewrote.rich.ru.nl/persons/dbab0086-38dc-4ee0-8d21-b9826e2f3d19/. 

De reden dat ze niet met 'Bosboom' te vinden is, is dat in de laatste WomenWriters twee *name componenten* zitten en alleen de eerste gebruikt is bij het importeren:

```json
"names": [
      {
        "components": [
          {
            "type": "FORENAME",
            "value": "Anna"
          },
          {
            "type": "FORENAME",
            "value": "Louisa"
          },
          {
            "type": "FORENAME",
            "value": "Geertruida"
          },
          {
            "type": "SURNAME",
            "value": "Toussaint"
          }
        ]
      },
      {
        "components": [
          {
            "type": "FORENAME",
            "value": "Anna"
          },
          {
            "type": "FORENAME",
            "value": "Louisa"
          },
          {
            "type": "FORENAME",
            "value": "Geertruida"
          },
          {
            "type": "SURNAME",
            "value": "Bosboom"
          },
          {
            "type": "SURNAME",
            "value": "- Toussaint"
          }
        ]
      }
    ],
```

Overigens heb ik bij alle objecten uit de laatste WomenWriters die geïmporteerd zijn, ook de originele data opgenomen. We kunnen dus daar makkelijk in kijken om er meer data uit te halen.

Overigens kan ik IDs die je noemt nergens vinden. Waar verwijzen ze precies naar?

**Comment by ACNMontoya** [comment]
In SHEWROTE zouden alle name components moeten worden geimporteerd, en de tweede (en volgende) zouden dan bij 'Alternative name' moeten worden gezet. De bedoeling is dan dat als je op één van die namen zoekt, je bij de record komt waaraan ze allemaal zijn vastgekoppeld. Dit is vrij essentieel, omdat vrouwen zo vaak van naam veranderen (en letterlijk dus hierdoor onvindbaar worden).

Als je een Person-Person relatie maakt, bedoel je dan een relatie tussen een vrouw-Person en haar echtegnoot-Persoon? Dat zou erg fijn zijn, als dat kan.

De twee IDs waren volgens mij twee screenshots die ik stuurde, om het verschil tussen de oude en nieuwe database te illustreren. De URLs zijn:

https://womenwriters.rich.ru.nl/womenwriters/vre/persons/dbab0086-38dc-4ee0-8d21-b9826e2f3d19#prevnext=1

https://shewrote.rich.ru.nl/persons/dbab0086-38dc-4ee0-8d21-b9826e2f3d19/

---


________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: dinsdag 20 augustus 2024 12:32
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Marriages setup (Issue #23)


De Person-Person-relatie kan ik wel maken, maar die bevat dan niet meer dan een short_name, gewoonweg omdat er niet meer in WomenWriters zit dan dat.

________________________________

Ik heb even gekeken of ik Geertruida Bosboom-Toussaint kon vinden en volgens mij is dit haar: https://test.shewrote.rich.ru.nl/persons/dbab0086-38dc-4ee0-8d21-b9826e2f3d19/.

De reden dat ze niet met 'Bosboom' te vinden is, is dat in de laatste WomenWriters twee name componenten zitten en alleen de eerste gebruikt is bij het importeren:

"names": [
      {
        "components": [
          {
            "type": "FORENAME",
            "value": "Anna"
          },
          {
            "type": "FORENAME",
            "value": "Louisa"
          },
          {
            "type": "FORENAME",
            "value": "Geertruida"
          },
          {
            "type": "SURNAME",
            "value": "Toussaint"
          }
        ]
      },
      {
        "components": [
          {
            "type": "FORENAME",
            "value": "Anna"
          },
          {
            "type": "FORENAME",
            "value": "Louisa"
          },
          {
            "type": "FORENAME",
            "value": "Geertruida"
          },
          {
            "type": "SURNAME",
            "value": "Bosboom"
          },
          {
            "type": "SURNAME",
            "value": "- Toussaint"
          }
        ]
      }
    ],

Overigens heb ik bij alle objecten uit de laatste WomenWriters die geïmporteerd zijn, ook de originele data opgenomen. We kunnen dus daar makkelijk in kijken om er meer data uit te halen.

Overigens kan ik IDs die je noemt nergens vinden. Waar verwijzen ze precies naar?

**Comment by vanlummelhuizen** [comment]
Ik heb AlternativeName-objecten aangemaakt mbv de originele data. Ook wordt er nu gezocht in AlternativeNames als je zoek op naam. Zie bv https://test.shewrote.rich.ru.nl/persons/?short_name=bosboom

Het is nu alleen nog op de test-server. Ik hoor graag of het ook naar de live-server kan.

**Comment by ACNMontoya** [comment]
Fijn, dank hiervoor. Het kan op de live-server.

Overigens, het is een andere Issue, maar 'maiden name' moet heten 'birth name'.

(Ik zet Floor verder in cc, omdat zij het probleem van Bosboom-Toussaint aankaartte.)

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 21 augustus 2024 13:01
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Marriages setup (Issue #23)


Ik heb AlternativeName-objecten aangemaakt mbv de originele data. Ook wordt er nu gezocht in AlternativeNames als je zoek op naam. Zie bv https://test.shewrote.rich.ru.nl/persons/?short_name=bosboom

Het is nu alleen nog op de test-server. Ik hoor graag of het ook naar de live-server kan.

**Comment by vanlummelhuizen** [comment]
> Het kan op de live-server.

Gedaan.



> Overigens, het is een andere Issue, maar 'maiden name' moet heten 'birth name'.

Dat staat in de planning: #26

**Comment by ACNMontoya** [comment]
Dank hiervoor!

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 21 augustus 2024 13:48
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Marriages setup (Issue #23)


Het kan op de live-server.

Gedaan.

Overigens, het is een andere Issue, maar 'maiden name' moet heten 'birth name'.

Dat staat in de planning: #26<https://github.com/tsg-humlab/shewrote/issues/26>

**Comment by vanlummelhuizen** [comment]
Ik heb inmiddels ook Marriage-objecten aangemaakt met de tempSpouse data. Zie bv https://test.shewrote.rich.ru.nl/persons/be085122-844d-4103-9377-2102abe8914a/#v-pills-personal: Margaret Maria Brewster is getrouwd met ene Gordon. Van die laatste heb ik dus een verder leeg Person-object gemaakt. Zie ook https://womenwriters.rich.ru.nl/womenwriters/vre/persons/be085122-844d-4103-9377-2102abe8914a/personal-situation.

Ik hoor weer graag of dit in orde is.

**Comment by ACNMontoya** [comment]
Dank hiervoor, dit lijkt mij goed zo.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 21 augustus 2024 14:43
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Marriages setup (Issue #23)


Ik heb inmiddels ook Marriage-objecten aangemaakt met de tempSpouse data. Zie bv https://test.shewrote.rich.ru.nl/persons/be085122-844d-4103-9377-2102abe8914a/#v-pills-personal: Margaret Maria Brewster is getrouwd met ene Gordon. Van die laatste heb ik dus een verder leeg Person-object gemaakt. Zie ook https://womenwriters.rich.ru.nl/womenwriters/vre/persons/be085122-844d-4103-9377-2102abe8914a/personal-situation.

Ik hoor weer graag of dit in orde is.

**Comment by vanlummelhuizen** [comment]
> Dank hiervoor, dit lijkt mij goed zo.

Dit heb ik zojuist ook op de live-server gedaan.

**Comment by vanlummelhuizen** [comment]
Ik zie dat er heel veel lege Person-objecten zijn aangemaakt, omdat ieder Person-object in WomenWriters een tempSpouse-veld had ook al was die leeg. Ik kan deze Person-objecten en de Marriage-objecten waar ze in zitten verwijderen. Goed idee?

**Comment by ACNMontoya** [comment]
Dit lijkt mij goed, zolang die echt helemaal leeg zijn.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: donderdag 22 augustus 2024 10:07
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Marriages setup (Issue #23)


Ik zie dat er heel veel lege Person-objecten zijn aangemaakt, omdat ieder Person-object in WomenWriters een tempSpouse-veld had ook al was die leeg. Ik kan deze Person-objecten en de Marriage-objecten waar ze in zitten verwijderen. Goed idee?

**Comment by vanlummelhuizen** [comment]
Ik test dat short_name, first_name en birth_name (voorheen maiden_name) leeg zijn. Zouden er Person-objecten kunnen zijn waarbij deze 3 velden leeg zijn maar toch moeten blijven bestaan?

**Comment by vanlummelhuizen** [comment]
Ik heb de test voor lege Person-objecten uitgebreid met bijna alle velden. Ik heb dit inmiddels op de test-server uitgevoerd. Kan je kijken of je dingen mist nu?

**Comment by ACNMontoya** [comment]
Bij Marriages lijkt het te kloppen (hoewel ik nu zie dat de data in de oude database echt helemaal vol staat met fouten).

Maar ik zie hier (nieuwe issue?) dat de gegevens van 'related to' lijken te zijn wegegvallen - en daarvoor in de plaats staat nu iets anders. Vergelijk de huidige SHEWROTE:

https://test.shewrote.rich.ru.nl/persons/ed7ca3f3-073f-404e-aaa2-9fde53e8f494/

met de oude versie van de data, waar er 9 Persons onder 'related to' staan:

https://womenwriters.rich.ru.nl/womenwriters/vre/persons/ed7ca3f3-073f-404e-aaa2-9fde53e8f494#prevnext=1

En hier ontbreken de 'related to' helemaal:

https://test.shewrote.rich.ru.nl/persons/440ea095-4667-4b5c-af4c-4c8781711916/

In de oude database zijn het er twee:

https://womenwriters.rich.ru.nl/womenwriters/vre/persons/440ea095-4667-4b5c-af4c-4c8781711916#prevnext=1


Het lijkt verder (nog een issue?) op de testserver alsof alle records zijn verdubbeld, bijv. hier: https://test.shewrote.rich.ru.nl/persons/?short_name=graffigny - en in sommige gevallen zelfs verdrievoudigd, bijv. https://test.shewrote.rich.ru.nl/persons/?short_name=george+sand of https://test.shewrote.rich.ru.nl/persons/?short_name=colette

En ten slotte nóf een nieuwe issue/verzoek: Kan 'Marital status' en alle informatie die eraan hangt ook visueel gescheiden worden van 'Personal situation' (= aparte kop maken op publieke interface)? Zo kan het hier - https://test.shewrote.rich.ru.nl/persons/4eee8ef9-28e8-42ee-9c14-0ebc672658e9/ - verwarrend zijn , en zou men kunnen denken dat 'religion' en de rest dat ná de naam van de man volgt op hem bewtrekking hebben.

Zo, het lijkt weer veel, maar stukje bij beetje komen we er wel.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: donderdag 22 augustus 2024 11:34
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Marriages setup (Issue #23)


Ik heb de test voor lege Person-objecten uitgebreid met bijna alle velden. Ik heb dit inmiddels op de test-server uitgevoerd. Kan je kijken of je dingen mist nu?

**Comment by vanlummelhuizen** [comment]
> Bij Marriages lijkt het te kloppen

Dan ga ik ook op de live-server de lege Person-objecten en bijbehorende Marriages verwijderen.

Van de rest van je opmerkingen heb ik nieuwe issues aangemaakt: #29, #30 en #31

**Comment by vanlummelhuizen** [comment]
> Dan ga ik ook op de live-server de lege Person-objecten en bijbehorende Marriages verwijderen.

Gedaan. Hierbij sluit ik dit issue.
