### ISSUE TITLE
Import Bibliography and Provisional notes from WomenWriters data

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#24]
@ACNMontoya 

Moet er voor **Provisional notes** een apart veld gemaakt worden, of kan het in het veld 'notes' komen? Indien dat laatste, wat moet er gebeuren als er al iets in 'notes' staat? 

Ook voor Bibliography: wat als er al iets in dat veld van Person staat?

**Comment by vanlummelhuizen** [comment]
Ik heb op de test-server de notes en bibliography uit de oude versie geïmporteerd. Zie bv https://test.shewrote.rich.ru.nl/persons/e98cf5f8-9a9b-4c5e-992c-b4d36a7eb50c/

Ik hoor graag of het in orde is en of het naar de live-server kan.

**Comment by ACNMontoya** [comment]
Beste Micha,

Dit ziet er goed uit, dank!

Hartelijks,
Alicia

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: dinsdag 9 juli 2024 15:11
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Import Bibliography and Provisional notes from WomenWriters data (Issue #24)


Ik heb op de test-server de notes en bibliography uit de oude versie geïmporteerd. Zie bv https://test.shewrote.rich.ru.nl/persons/e98cf5f8-9a9b-4c5e-992c-b4d36a7eb50c/

Ik hoor graag of het in orde is en of het naar de live-server kan.

**Comment by vanlummelhuizen** [comment]
OK. Het staat nu ook op de live-server.

Ik sluit hiermee dit issue.

**Comment by ACNMontoya** [comment]
Beste Micha en Dennis,

Iets dat ik vergat te vragen. Kan 'maiden name' worden herbenoemd in 'birth name' (bij Person)?

Hartelijks,
Alicia

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>
