### ISSUE TITLE
Rename 'maiden name' to 'birth name' for Person

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#26]
Beste Micha en Dennis,

Iets dat ik vergat te vragen. Kan 'maiden name' worden herbenoemd in 'birth name' (bij Person)?

Hartelijks,
Alicia

**Comment by vanlummelhuizen** [comment]
@Alicia @dennis-bor 

Ik heb voor dit verzoek even dit issue gemaakt.

**Comment by vanlummelhuizen** [comment]
De wijziging staat nu op de test-server. Ik hoor graag of het in orde is.

**Comment by ACNMontoya** [comment]
Dank hiervoor!

A

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: donderdag 22 augustus 2024 10:52
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Rename 'maiden name' to 'birth name' for Person (Issue #26)


Assigned #26<https://github.com/tsg-humlab/shewrote/issues/26> to @ACNMontoya<https://github.com/ACNMontoya>.

**Comment by vanlummelhuizen** [comment]
Inmiddels ook op de live-server. 

Ik sluit hiermee dit issue.
