### ISSUE TITLE
Remove ReceptionReceptionType and it's usages

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#28]

**Comment by vanlummelhuizen** [comment]
@ACNMontoya @dennis-bor 

Ik heb ReceptionReceptionType geheel uit de code verwijderd. Het tabblad Types bij een Reception is danook verdwenen.

De wijzigingen staan op de test-server. Ik hoor graag of het in orde is en of het naar de live-server kan.

**Comment by ACNMontoya** [comment]
Dank, dit lijkt mij goed zo.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: maandag 15 juli 2024 11:22
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Remove ReceptionReceptionType and it's usages (Issue #28)


@ACNMontoya<https://github.com/ACNMontoya> @dennis-bor<https://github.com/dennis-bor>

Ik heb ReceptionReceptionType geheel uit de code verwijderd. Het tabblad Types bij een Reception is danook verdwenen.

De wijzigingen staan op de test-server. Ik hoor graag of het in orde is en of het naar de live-server kan.

**Comment by vanlummelhuizen** [comment]
Het staat op de live-server.

Ik sluit hierbij dit issue.
