### ISSUE TITLE
Check Related-to data from WomenWriters to Shewrote

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#29]
Van @ACNMontoya (https://github.com/tsg-humlab/shewrote/issues/23#issuecomment-2304340315):

Maar ik zie hier (nieuwe issue?) dat de gegevens van 'related to' lijken te zijn wegegvallen - en daarvoor in de plaats staat nu iets anders. Vergelijk de huidige SHEWROTE:

https://test.shewrote.rich.ru.nl/persons/ed7ca3f3-073f-404e-aaa2-9fde53e8f494/

met de oude versie van de data, waar er 9 Persons onder 'related to' staan:

https://womenwriters.rich.ru.nl/womenwriters/vre/persons/ed7ca3f3-073f-404e-aaa2-9fde53e8f494#prevnext=1

En hier ontbreken de 'related to' helemaal:

https://test.shewrote.rich.ru.nl/persons/440ea095-4667-4b5c-af4c-4c8781711916/

In de oude database zijn het er twee:

https://womenwriters.rich.ru.nl/womenwriters/vre/persons/440ea095-4667-4b5c-af4c-4c8781711916#prevnext=1

**Comment by vanlummelhuizen** [comment]
Ik heb met een script de related_to info opgehaald. Kan je eens kijken op de test-server of het zo klopt?

**Comment by ACNMontoya** [comment]
Dit ziet er goed uit.

Voor de volledigheid, ik had ook aangeveen (nieuwe issue?) dat het nog mogelijk zou moeten zijn om een RelationType aan te geven (kiezen uit een gesloten menu, meerdere keuzes mogelijk).


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: donderdag 22 augustus 2024 15:26
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Check Related-to data from WomenWriters to Shewrote (Issue #29)


Ik heb met een script de related_to info opgehaald. Kan je eens kijken op de test-server of het zo klopt?

**Comment by vanlummelhuizen** [comment]
Op live heb ik nu ook de related_to info opgehaald. De wens voor een RelationType wordt behandeld in #32. 

Ik sluit dit issue.
