### ISSUE TITLE
Find (and remove?) duplicate Persons

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#30]
Van @ACNMontoya (https://github.com/tsg-humlab/shewrote/issues/23#issuecomment-2304340315):

Het lijkt verder (nog een issue?) op de testserver alsof alle records zijn verdubbeld, bijv. hier: https://test.shewrote.rich.ru.nl/persons/?short_name=graffigny - en in sommige gevallen zelfs verdrievoudigd, bijv. https://test.shewrote.rich.ru.nl/persons/?short_name=george+sand of https://test.shewrote.rich.ru.nl/persons/?short_name=colette

**Comment by vanlummelhuizen** [comment]
Dit was gelukkig een makkelijke: ze werden (drie)dubbel weergegeven, maar zaten niet (drie)dubbel in de database.

Ik heb het op de test-server opgelost. Indien in orde, zet ik het ook meteen op de live-server.

**Comment by ACNMontoya** [comment]
Prima, dank, fijn dat er af en toe ook een makkie ertussen zit 😉





________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: donderdag 22 augustus 2024 13:44
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Find (and remove?) duplicate Persons (Issue #30)


Dit was gelukkig een makkelijke: ze werden (drie)dubbel weergegeven, maar zaten niet (drie)dubbel in de database.

Ik heb het op de test-server opgelost. Indien in orde, zet ik het ook meteen op de live-server.

**Comment by vanlummelhuizen** [comment]
> zet ik het ook meteen op de live-server.

Gedaan. En sluiten
