### ISSUE TITLE
Move Marriage info to separate section in detail view

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#31]
Van @ACNMontoya (https://github.com/tsg-humlab/shewrote/issues/23#issuecomment-2304340315):

En ten slotte nóf een nieuwe issue/verzoek: Kan 'Marital status' en alle informatie die eraan hangt ook visueel gescheiden worden van 'Personal situation' (= aparte kop maken op publieke interface)? Zo kan het hier - https://test.shewrote.rich.ru.nl/persons/4eee8ef9-28e8-42ee-9c14-0ebc672658e9/ - verwarrend zijn , en zou men kunnen denken dat 'religion' en de rest dat ná de naam van de man volgt op hem bewtrekking hebben.

**Comment by dennis-bor** [comment]
Marital status is nu een apart kopje onder Details van een Person. Dit staat inmiddels op de test server.
@ACNMontoya zou je kunnen kijken of dit oke is?

**Comment by ACNMontoya** [comment]
Dank, dit ziet er goed uit.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Dennis Bor ***@***.***>
Verzonden: dinsdag 10 september 2024 14:23
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Move Marriage info to separate section in detail view (Issue #31)


Marital status is nu een apart kopje onder Details van een Person. Dit staat inmiddels op de test server.
@ACNMontoya<https://github.com/ACNMontoya> zou je kunnen kijken of dit oke is?

**Comment by vanlummelhuizen** [comment]
Dit staat nu ook op de live-server dus ik sluit dit issue.
