### ISSUE TITLE
Add PersonPersonRelationType model

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#32]
See https://github.com/tsg-humlab/shewrote/issues/29#issuecomment-2304883079

> ik had ook aangeveen (nieuwe issue?) dat het nog mogelijk zou moeten zijn om een RelationType aan te geven (kiezen uit een gesloten menu, meerdere keuzes mogelijk).

**Comment by vanlummelhuizen** [comment]
@ACNMontoya 

Wat voor RelationTypes zullen er zijn? Kun je voorbeelden geven? 

Zijn er RelationTypes die niet voor beide richtingen gelijkt zijn?  Bijvoorbeeld oom-neef/nicht of werkgever-werknemer? In tegenstelling tot gelijkwaardige typen: familie, collega.

**Comment by ACNMontoya** [comment]
Dit zijn de relations die we hebben afgesproken:

Collaborator
Friend
Sibling
Family: non-household
Professional colleague
Correspondent

Religious tutor of
Student of
Protégé of
Mentor of

De eerste set zijn bidirectional, de tweede niet.

Hartelijks,
Alicia

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 28 augustus 2024 11:55
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add PersonPersonRelationType model (Issue #32)


@ACNMontoya<https://github.com/ACNMontoya>

Wat voor RelationTypes zullen er zijn? Kun je voorbeelden geven?

Zijn er RelationTypes die niet voor beide richtingen gelijkt zijn? Bijvoorbeeld oom-neef/nicht of werkgever-werknemer? In tegenstelling tot gelijkwaardige typen: familie, collega.

**Comment by vanlummelhuizen** [comment]
Ik heb RelationType toegevoegd op de test-server. Voor je het kan gebruiken in het tabblad Relations van een person, moet je er eerst enkele aanmaken. Hierbij moet je er voor de non-bidirectional types twee aanmaken en die naar elkaar laten verwijzen:

1. maak de eerste van de twee aan op https://test.shewrote.rich.ru.nl/admin/shewrote/relationtype/add/: vul *text* in en laat *reverse* leeg.
2. maak via dezelfde url een tweede aan: vul weer *text* in en kies bij *reverse* het relation-type dat je bij 1 hebt aangemaakt. 

Bij 2 wordt automatisch de tweede relation-type ingevuld in *reverse* van de eerste, zodat ze elkaar 'zien' via *reverse*. 

Nu kan je ze gebruiken op het tabblad Relations van een person. Je kan daar meerdere relation-types selecteren per relatie. Nadat je hebt gesaved, worden de types ook toegevoegd aan de tegenovergestelde relatie en eventueel omgedraaid als het een non-bidirectional relatie-type is.

Ik hoor weer graag of het goed werkt (en naar live kan) of dat het anders moet.

**Comment by vanlummelhuizen** [comment]
@ACNMontoya Kan je kijken of dit nu in orde is? Het staat al op de live-server.

**Comment by ACNMontoya** [comment]
Om een relation type aan te kunnen geven bij een al bestaande person_person_relation, zou het handig zijn te kunnen zoeken in de al bestaande relations. Het zijn er namelijk 2,757, te veel om doorheen te scrollen. Kan er een zoekscherm hiervoor komen in de Admin?

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: dinsdag 10 september 2024 10:43
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add PersonPersonRelationType model (Issue #32)


@ACNMontoya<https://github.com/ACNMontoya> Kan je kijken of dit nu in orde is? Het staat al op de live-server.

**Comment by vanlummelhuizen** [comment]
Geen probleem om dat te doen. Hoe wil je precies zoeken?

Is er een speciale reden om direct in PersonPersonRelation te willen zoeken en editen? Je kan relation types namelijk ook toevoegen bij Person, bv https://shewrote.rich.ru.nl/admin/shewrote/person/2d78f76c-56bd-4273-bf2f-4e78f524a3e2/change/?_to_field=id#relations

**Comment by ACNMontoya** [comment]
Wanneer ik het direct in Person probeer te veranderen, krijg ik de melding Bad request (400).

Ook zie ik dat er in de front-end geen plek is waarop het type Relation wordt aangegeven.

Tenslotte een andere vrag: is het een goed idee om 'child of' onder de PersonPersonRelationTypes te zetten, gezien er al een veld 'Children' bestaat (die je echter niet kunt editen), of gaan dingen dan door elkaar lopen?

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 11 september 2024 12:14
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add PersonPersonRelationType model (Issue #32)


Geen probleem om dat te doen. Hoe wil je precies zoeken?

Is er een speciale reden om direct in PersonPersonRelation te willen zoeken en editen? Je kan relation types namelijk ook toevoegen bij Person, bv https://shewrote.rich.ru.nl/admin/shewrote/person/2d78f76c-56bd-4273-bf2f-4e78f524a3e2/change/?_to_field=id#relations

**Comment by ACNMontoya** [comment]
Nu een grote issue: we zouden graag in de nieuwe SHEWROTE dezelfde soort faceted searches mogelijk willen maken als in de oude WomenWriters, NEWW Women Writers (ru.nl)<https://womenwriters.rich.ru.nl/womenwriters/vre/persons#q=%7B%22authors%22%3A%7B%22searchFields%22%3A%5B%5D%2C%22sortFields%22%3A%5B%5D%7D%2C%22publications%22%3A%7B%22searchFields%22%3A%5B%5D%2C%22sortFields%22%3A%5B%5D%7D%2C%22authorReceptions%22%3A%7B%22searchFields%22%3A%5B%5D%2C%22sortFields%22%3A%5B%5D%7D%2C%22publicationReceptions%22%3A%7B%22searchFields%22%3A%5B%5D%2C%22sortFields%22%3A%5B%5D%7D%7D>.

Bij Author: filteren op sex, country, year of birth, year of death, enz.

Bij Works: filteren op publication year, language of first publication, genre, notes, en number of editions (deze laatste is nieuw)

Bij Receptions: filteren op reception type, reception author, reception year, reception country, en notes.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 11 september 2024 13:38
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add PersonPersonRelationType model (Issue #32)


Tenslotte een andere vrag: is het een goed idee om 'child of' onder de PersonPersonRelationTypes te zetten, gezien er al een veld 'Children' bestaat (die je echter niet kunt editen), of gaan dingen dan door elkaar lopen?

Een Person heeft een mother en een father veld die je wel kan wijzigen, zie bv. https://shewrote.rich.ru.nl/admin/shewrote/person/2d78f76c-56bd-4273-bf2f-4e78f524a3e2/change/?_to_field=id#parents Daar komen ook de Children vandaan (tegenovergestelde relatie).

**Comment by vanlummelhuizen** [comment]
Nieuw issue #42
