### ISSUE TITLE
Add Collectives to front end

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#34]
@ACNMontoya schreef (https://github.com/tsg-humlab/shewrote/issues/22#issuecomment-2334204294):

Kan Collectives in de frontend geimplementeerd worden, zodat gebruikers kunnen klikken op een Collective om alle leden ervan te zien?

En kan er een knop voor Collectives komen na Persons op de bovenbalk?

**Comment by vanlummelhuizen** [comment]
Ik heb op de test-server Collectives toegevoegd: https://test.shewrote.rich.ru.nl/collectives/

**Comment by vanlummelhuizen** [comment]
Dit staat nu ook op de live-server want het is meegekomen met de implementaties voor bv #31 en #35. In orde zo?

**Comment by ACNMontoya** [comment]
Dank, prima zo (maar ik maak zo meteen een nieuwe issue aan m.b.t. Collectives)

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 11 september 2024 09:33
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add Collectives to front end (Issue #34)


Dit staat nu ook op de live-server want het is meegekomen met de implementaties voor bv #31<https://github.com/tsg-humlab/shewrote/issues/31> en #35<https://github.com/tsg-humlab/shewrote/issues/35>. In orde zo?
