### ISSUE TITLE
Afbeelding in Persons lijst

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#35]
@ACNMontoya schreef:

> Nog een verzoek: zou het mogelijk zijn om op de Persons startpagina met de lange lijst namen ook een postzegel-formaat afbeelding op te nemen bij degenen die dat hebben?

**Comment by vanlummelhuizen** [comment]
Dit staat op de test-server. Ik hoor graag of het in orde is.

**Comment by ACNMontoya** [comment]
Mooi zo, dank!

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 11 september 2024 09:30
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Afbeelding in Persons lijst (Issue #35)


@ACNMontoya<https://github.com/ACNMontoya> Dit staat nu ook op de live-server, zie bv. https://shewrote.rich.ru.nl/persons/?short_name=behn. In orde zo?
