### ISSUE TITLE
Add Place field in Collective form in admin

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#38]
@ACNMontoya schreef:

>  Is het mogelijk om bij Collective place in de Admin een zoekveld te maken, zodat wij bij het editen snel de plaats kunnen kiezen uit de lange drop-down lijst?

> Beter nog zou het zijn als in de Collective formulier meteen ook Place stond (niet een aparte Collective place), want nu is het dubbel werk om die aan te maken.

**Comment by ACNMontoya** [comment]
Excuus, ik zie nu iets anders, namelijk dat wanneer je in de front-end op Collectives klikt om de hele lijst op te halen, staat er in de kop  'Persons'. Dat moet uiteraard ook 'Collectives' zijn.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 11 september 2024 11:16
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: [tsg-humlab/shewrote] Add Place field in Collective form in admin (Issue #38)


@ACNMontoya<https://github.com/ACNMontoya> schreef:

Is het mogelijk om bij Collective place in de Admin een zoekveld te maken, zodat wij bij het editen snel de plaats kunnen kiezen uit de lange drop-down lijst?

Beter nog zou het zijn als in de Collective formulier meteen ook Place stond (niet een aparte Collective place), want nu is het dubbel werk om die aan te maken.

**Comment by vanlummelhuizen** [comment]
> Excuus, ik zie nu iets anders, namelijk dat wanneer je in de front-end op Collectives klikt om de hele lijst op te halen, staat er in de kop 'Persons'. Dat moet uiteraard ook 'Collectives' zijn.

Dit is gedaan en staat ook al op de live-server.

**Comment by ACNMontoya** [comment]
Mooi, dank!

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 11 september 2024 11:58
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add Place field in Collective form in admin (Issue #38)


Excuus, ik zie nu iets anders, namelijk dat wanneer je in de front-end op Collectives klikt om de hele lijst op te halen, staat er in de kop 'Persons'. Dat moet uiteraard ook 'Collectives' zijn.

Dit is gedaan en staat ook al op de live-server.

**Comment by dennis-bor** [comment]
In de admin pagina kun je bij het maken van een nieuw (of editen van een bestaand) Collective nu place(s) toevoegen. Dit staat op de test versie. Ik hoor graag of dit zo goed is.

**Comment by ACNMontoya** [comment]
Dank, dit werkt goed zo.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Dennis Bor ***@***.***>
Verzonden: donderdag 12 september 2024 12:38
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add Place field in Collective form in admin (Issue #38)


In de admin pagina kun je bij het maken van een nieuw (of editen van een bestaand) Collective nu place(s) toevoegen. Dit staat op de test versie. Ik hoor graag of dit zo goed is.

**Comment by ACNMontoya** [comment]
Graag zou ik meerdere Places of publication kunnen aangeven bij Edition.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Montoya, A.C. (Alicia) ***@***.***>
Verzonden: donderdag 12 september 2024 13:23
Aan: tsg-humlab/shewrote ***@***.***>; tsg-humlab/shewrote ***@***.***>
CC: Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add Place field in Collective form in admin (Issue #38)

Dank, dit werkt goed zo.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Dennis Bor ***@***.***>
Verzonden: donderdag 12 september 2024 12:38
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add Place field in Collective form in admin (Issue #38)


In de admin pagina kun je bij het maken van een nieuw (of editen van een bestaand) Collective nu place(s) toevoegen. Dit staat op de test versie. Ik hoor graag of dit zo goed is.

**Comment by vanlummelhuizen** [comment]
> Graag zou ik meerdere Places of publication kunnen aangeven bij Edition.

Ik heb een nieuw issue hiervoor gemaakt: #41

**Comment by ACNMontoya** [comment]
Deze knop (onder Persons, in de front-end van SHEWROTE) reageert niet, al meer dan een week.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>




________________________________
From: Montoya, A.C. (Alicia) ***@***.***>
Sent: Friday, September 20, 2024 10:08
To: Montoya, A.C. (Alicia) ***@***.***>; tsg-humlab/shewrote ***@***.***>; tsg-humlab/shewrote ***@***.***>
Cc: Mention ***@***.***>
Subject: new issue: meerdere Places of publication bij Edition

Graag zou ik meerdere Places of publication kunnen aangeven bij Edition.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Montoya, A.C. (Alicia) ***@***.***>
Verzonden: donderdag 12 september 2024 13:23
Aan: tsg-humlab/shewrote ***@***.***>; tsg-humlab/shewrote ***@***.***>
CC: Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add Place field in Collective form in admin (Issue #38)

Dank, dit werkt goed zo.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Dennis Bor ***@***.***>
Verzonden: donderdag 12 september 2024 12:38
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add Place field in Collective form in admin (Issue #38)


In de admin pagina kun je bij het maken van een nieuw (of editen van een bestaand) Collective nu place(s) toevoegen. Dit staat op de test versie. Ik hoor graag of dit zo goed is.

**Comment by vanlummelhuizen** [comment]
Als je de knop `View full list of record editors`  bedoelt, die heb ik nu gefixt.

**Comment by ACNMontoya** [comment]
Dank hiervoor!


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
