### ISSUE TITLE
in Persons front-end: doorklikmogelijkheid maken vanuit Collectives (onder Memberships)

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#40]
@ACNMontoya kan je dit wat verduidelijken?

**Comment by ACNMontoya** [comment]
Graag. Het zou mogelijk moeten zijn wanneer je in de front-end onder een Person ziet dat zij lid is geweest van een Collective (memberships) om op de naam van de Collective te kunnen klikken om zo meteen naar de Collective zelf te gaan, om de volledige ledenlijst te zien (voor zover in de DB aanwezig). Nu moet je eerst naar Collectives gaan, en dan de naam intikken en daarop zoeken (drie extra handelingen, die ongeduldige wetenschappers liever overslaan).

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 11 september 2024 12:03
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: [tsg-humlab/shewrote] in Persons front-end: doorklikmogelijkheid maken vanuit Collectives (onder Memberships) (Issue #40)


@ACNMontoya<https://github.com/ACNMontoya> kan je dit wat verduidelijken?

**Comment by vanlummelhuizen** [comment]
Duidelijk wat mij betreft. Ik denk dat dit niet erg ingewikkeld is.

**Comment by vanlummelhuizen** [comment]
I have made something but before I can put it on the test-server, I first need to know whether the functionality we discuss in #43 is ready to be merge into the main (well 'develop') branch.

**Comment by vanlummelhuizen** [comment]
Dit is op de test-server, bv https://test.shewrote.rich.ru.nl/persons/d807694f-733b-4ba1-bca0-b1e5a6645885/#v-pills-profession

**Comment by ACNMontoya** [comment]
Mooi, dank, het kan zo nar de live server.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: donderdag 26 september 2024 16:13
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] in Persons front-end: doorklikmogelijkheid maken vanuit Collectives (onder Memberships) (Issue #40)


Dit is op de test-server, bv https://test.shewrote.rich.ru.nl/persons/d807694f-733b-4ba1-bca0-b1e5a6645885/#v-pills-profession

**Comment by vanlummelhuizen** [comment]
Dit staat op de live-server. Ik sluit daarom dit issue.
