### ISSUE TITLE
Add page to list/search for editors

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#43]
> Ook moet het mogelijk worden voor gebruikers om in de lijst van editors te zoeken, zodat iemand die heeft bijgedragen aan de DB een lijst kan genereren bijv. ter verantwoording bij haar onderzoeksinstituut (die graag ons onderzoeksoutput bijhoudt en kwantificeert).

**Comment by vanlummelhuizen** [comment]
@ACNMontoya 

Ik heb het nu zo gemaakt dat als je rechtsboven op je gebruikersnaam klikt, dat je je eigen changes/contributions te zien krijgt. De links van de records gaan naar de admin. Ik heb dit vooral gedaan omdat niet alle wijzigingen betrekking hebben op records die een pagina in de frontend hebben (bv. een marriage, period_of_residence etc).

Te testen op de test-server. Ik hoor weer graag of het in orde is.

**Comment by vanlummelhuizen** [comment]
Switch to English?

It would involve connecting old users (created from first WomenWriters) with new users and then merge the changes-info in some way.

The connecting could be done by the users themselves or by admins for more supervision.

The merging could be done by replacing the old users with the new users in the list of changes. In some way this is like changing history. The alternative is to keep a list of connections between old and new users and with that list lookup the changes made by both the old and new user. The latter solution is probably a bit harder to implement, but does not change anything to the underlying data.

**Comment by vanlummelhuizen** [comment]
Is the functionality for showing changes satisfactory, given that we solve connecting old and new users later?

**Comment by ACNMontoya** [comment]
Ja, het werkt prima. Voor het mergen lijkt het mij idd niet goed om aan de oude data te gaan sleutelen. Als er een search mogelijkheid is, waarbij mensen de edits kunnen opzoeken onder verschillende namen, zou dat het probleem oplossen.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: donderdag 26 september 2024 14:40
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add page to list/search for editors (Issue #43)


Is the functionality for showing changes satisfactory, given that we solve connecting old and new users later?

**Comment by ACNMontoya** [comment]
Ja, dat is prima, dan ook de edits van anderen opzoekbaar zijn.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: donderdag 26 september 2024 16:01
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add page to list/search for editors (Issue #43)


Als er een search mogelijkheid is, waarbij mensen de edits kunnen opzoeken onder verschillende namen, zou dat het probleem oplossen.

OK. NB dan kunnen users ook changes van andere users zien.

**Comment by vanlummelhuizen** [comment]
Ik heb een selectieveld met zoek mogelijkheid toegevoegd waarmee je een andere gebruiker kan kiezen: https://test.shewrote.rich.ru.nl/changes/.

**Comment by ACNMontoya** [comment]
Ik heb dit uitgeprobeerd, maar wanneer ik op een andere gebruiker klik, krijg ik een lange lijst met telkens de melding 'No representation', in plaats van de naam van de Work, Person of Reception  die ze hebben ge-edit.

[cid:1e4d682b-53e7-4105-bd83-3fd12270a9a1]

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: woensdag 2 oktober 2024 10:42
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add page to list/search for editors (Issue #43)


Ik heb een selectieveld met zoek mogelijkheid toegevoegd waarmee je een andere gebruiker kan kiezen: https://test.shewrote.rich.ru.nl/changes/.

**Comment by vanlummelhuizen** [comment]
In een 'change'-object in SHEWROTE (CRUDEvent genaamd) kan een representation opgenomen zijn. Dat is handig bij het maken van een lijst met changes. 

Bij het importeren van de changes uit de eerste WomenWriters heb ik echter niks als representatie opgenomen. Wat ik zou kunnen doen is een representie opnemen van het huidige object waar een CRUDEvent naar verwijst.

**Comment by vanlummelhuizen** [comment]
Met een representation bedoel ik (of eigenlijk het systeem dat wijzingen bijjhoudt) een korte tekst waarmee een object geïdentificeerd kan worden. Ik heb nu overal waar nog geen representation stond, de name of short_name ingevuld.

Dit staat nu ook op de live-server. Zie bijvoorbeeld https://shewrote.rich.ru.nl/changes/?user=41: hier stond voorheen steeds 'NO REPRESENTATION'.

Ik hoor graag of het in orde is.

**Comment by vanlummelhuizen** [comment]
Ter referentie voor @vanlummelhuizen en @dennis-bor: lege `CRUDEvent.object_repr' zijn als volgt gevuld:

```python
from easyaudit.models import CRUDEvent

crud_events = []
for ce in CRUDEvent.objects.filter(object_repr__isnull=True):
    ce.object_repr = str(ce.content_type.get_object_for_this_type(id=ce.object_id))
    crud_events.append(ce)

CRUDEvent.objects.bulk_update(crud_events, ['object_repr'])

```

**Comment by ACNMontoya** [comment]
Mooi, dank hiervoor!


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
Van: Micha Hulsbosch ***@***.***>
Verzonden: dinsdag 8 oktober 2024 11:41
Aan: tsg-humlab/shewrote ***@***.***>
CC: Montoya, A.C. (Alicia) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tsg-humlab/shewrote] Add page to list/search for editors (Issue #43)


Met een representation bedoel ik (of eigenlijk het systeem dat wijzingen bijjhoudt) een korte tekst waarmee een object geïdentificeerd kan worden. Ik heb nu overal waar nog geen representation stond, de name of short_name ingevuld.

Dit staat nu ook op de live-server. Zie bijvoorbeeld https://shewrote.rich.ru.nl/changes/?user=41: hier stond voorheen steeds 'NO REPRESENTATION'.

Ik hoor graag of het in orde is.
