### ISSUE TITLE
Add 'created' and 'last edited' info of second version of WomenWriters

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#44]
> Kun je ook de 'created' en 'last modified' info uit de 2e versie van de database zichtbaar maken in SHEWROTE? Dat zou heel fijn zijn, als we all editor informatie bij elkaar kunnen tonen bij elke record.

**Comment by vanlummelhuizen** [comment]
@ACNMontoya 

In de data van de 2e versie zitten drie velden die de identiteit van de gebruiker aangeven: 

* username: een persoonsnaam, meestal voor- en achternaam, maar niet altijd
* userId:  een ID-code in 3 vormen: [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier), 'importer' of USER0000000000?? waarbij de vraagtekens een steeds wisselend nummer is
* vreId: cwno, cwrs, neww, WomenWriters of niks

Hoe zal ik deze info in de username van Shewrote opnemen zodat ze gevonden kunnen worden? Ik zou ze bijvoorbeeld alle drie kunnen opnemen of twee van de drie of slechts een. En indien meerdere, hoe moet ik ze aan elkaar plakken? Met een spatie, komma, apestaartje, streepje, plusteken, underscore?

**Comment by ACNMontoya** [comment]
Voor de eindgebruiker is de username de belangrijkste, als je alleen die kunt opnemen zou dat voor ons voldoende zijn.

Overigens zullen we in een later stadium moeten kijken hoe we eventueel usernames bij elkaar kunnen bundelen, want ik zie dat dezelfde gebruiker vaak meerdere usernames heeft (bij nieuw aangemaakte inlogcodes, bijvoorbeeld).


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
De created/modified data van de tweede WomenWriters zit nu ook in de database van de live-server. Zie https://shewrote.rich.ru.nl/admin/easyaudit/crudevent/.

> Overigens zullen we in een later stadium moeten kijken hoe we eventueel usernames bij elkaar kunnen bundelen, want ik zie dat dezelfde gebruiker vaak meerdere usernames heeft (bij nieuw aangemaakte inlogcodes, bijvoorbeeld).

Zie #72 

Ik sluit hiermee dit issue.

**Comment by ACNMontoya** [comment]
Mooi, dank!


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
