### ISSUE TITLE
Add Related To section on Person details page

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#46]
> Graag wil ik op de Person display page een aparte kopje hebben voor 'Related to' (na Marital Status). Daarin komen de verschillende Persons onder ' related to' elk op een nieuwe regel, met telkens na de naam de 'relation type'. Aan die 'relation type'  moeten t.z.t. ook (optionele) data komen te hangen - maar dat is weer een nieuwe issue.

**Comment by vanlummelhuizen** [comment]
@ACNMontoya Deze heb ik nu op de test-server: https://test.shewrote.rich.ru.nl/persons/e1535850-b645-4b59-85cb-663db60c1a10/#v-pills-relation

**Comment by ACNMontoya** [comment]
Mooi, dank, hij kan zo naar live.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Gedaan. Ik sluit dit issue.
