### ISSUE TITLE
Add Bibliography and Provisional Notes to the bottom of Person details Page

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#47]
> Verder graag de Bibliography en Provisional Notes onderaan de display pagina zetten.

**Comment by vanlummelhuizen** [comment]
> Dit staat op de test-server. Bijvoorbeeld https://test.shewrote.rich.ru.nl/persons/ed7ca3f3-073f-404e-aaa2-9fde53e8f494/#v-pills-bibliography

@ACNMontoya kan je kijken of dit in orde is? Ik ben nu bezig met issue #58 en #65.

**Comment by ACNMontoya** [comment]
Dank, dit kan zo naar de live versie.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Dit staat alweer een tijdje op de live-server. Ik sluit daarom dit issue.
