### ISSUE TITLE
Remove quotes around model name in ForeignKey field

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#5]
See for instance `'Place'` in https://github.com/tsg-humlab/shewrote/blob/dde56bccbf2b4c8dc9ddc2c69b9281a521c36130/shewrote/models.py#L34

If there are no quotes it is easier to navigate in your IDE.

**Comment by vanlummelhuizen** [comment]
.. and ManyToMany fields

**Comment by dennis-bor** [comment]
Removing the quotes makes it that django cannot resolve the reference to Place, because Place is defined later. We might be able to resolve this after we straighten out the FK and M2M relationships.

**Comment by vanlummelhuizen** [comment]
I think you can solve this by changing the order of the models in the file. Things higher up are defined before things lower in the file.
