### ISSUE TITLE
Add  'TEMP MARRIAGE' to short name of spouses

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#51]
> Zou het mogelijk zijn om al deze 'temporary spouse'  records duidelijk zo te markeren, bijvoorbeeld door toevoeging in de 'short name'  veld van TEMP MARRIAGE? Dan kunnen we die records gerichter gaan opschonen.

**Comment by vanlummelhuizen** [comment]
@ACNMontoya 

Ik heb dit op de test-server gedaan. Zie https://test.shewrote.rich.ru.nl/persons/?short_name=TEMP+MARRIAGE

**Comment by ACNMontoya** [comment]
Dank hiervoor, dit lijkt mij goed werkbaar zo. Ik neem dat de edits die inmiddels in de live database op een aantal van deze records zijn gemaakt wel bewaard blijven?


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Hmm, ik heb even naar een aantal records gekeken en ik denk dat mijn methode niet gaat werken voor de huidige staat van de data. De methode zocht naar Persons met een spouse die iets in tempSpouse heeft staan en die Persons kregen TEMP MARRIAGE achter hun short name. Ik zie echter dat er ook nieuwe Persons zijn die in een Marriage zitten en omdat ze nieuw zijn, geen tempSpouse (of uberhaupt original data) hebben. Bijvoorbeeld https://shewrote.rich.ru.nl/persons/4976260f-dd0c-4591-96a1-fccabcdb9350/. Deze zou dan ook TEMP MARRIAGE achter de short name krijgen, maar dat lijkt me niet wenselijk.

**Comment by vanlummelhuizen** [comment]
Bovengenoemde Person is niet een aangepast record maar een nieuw record. Is het daarvoor ook OK? Ik kan nog een andere manier van Persons selecteren proberen.

**Comment by vanlummelhuizen** [comment]
Ik heb nu een methode die alleen Persons meeneemt die in een Marriage zitten die ik vanuit de tempSpouse-data heb aangemaakt. Dat zijn 1615 Persons. Mijn eerdere methode had er 1640. Zal ik deze laatste methode toepassen?

**Comment by ACNMontoya** [comment]
Ja, graag toepassen, dank vast hiervoor!


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Gedaan: https://shewrote.rich.ru.nl/persons/?short_name=TEMP+MARRIAGE
