### ISSUE TITLE
Turn SHEWROTE link in the navigation into a menu

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#55]
>  Op de SHEWROTE beginpagina willen wij verder onder de kop SHEWROTE in het lintje bovenaan drie klikmogelijkheden: 
> 
>       DARIAH-EU Working Group
>       Huizinga Institute Research Network
>       Other databases on women's writing 
> 
> De eerste twee moeten linken naar de sites waarnaar al elders op de pagina wordt gelinkd. De laatste (Other databases on women's writing) zou naar een pagina meoten leiden waar de informatie staat die ik in bijgesloten document heb gezet. Ik neem aan dat dit op de database kan worden gezet vóór december?

**Comment by vanlummelhuizen** [comment]
@ACNMontoya Wat zijn de urls van de links?

**Comment by ACNMontoya** [comment]
DARIAH-EU Working Group:     
https://www.dariah.eu/activities/working-groups/women-writers-in-history/


Huizinga Institute Research Network:
https://www.huizingainstituut.nl/working-group/womens-writing-history/

      
Other databases on women's writing - lijst in attachment

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Zie ook https://github.com/tsg-humlab/shewrote/issues/22#issuecomment-2482265607

**Comment by vanlummelhuizen** [comment]
SHEWROTE in het lint is nu een dropdown menu met de gevraagde items op de Sources na (zie https://github.com/tsg-humlab/shewrote/issues/22#issuecomment-2482265607). Het staat op de test-server.

**Comment by vanlummelhuizen** [comment]
Het eerste deel (alles behalve https://github.com/tsg-humlab/shewrote/issues/22#issuecomment-2482265607) staat nu op de live server.

**Comment by vanlummelhuizen** [comment]
Voor https://github.com/tsg-humlab/shewrote/issues/22#issuecomment-2482265607 heb ik in het SHEWROTE-menu onderaan een nieuw item toegevoegd: Sources. De lijst die je dan krijgt zijn nog wel Work-objecten, maar op basis van de originele data uit WomenWriters (*isDocumentSourceOf* relatie) worden ze gevonden als Source. Bij Works in de front-end worden ze weggelaten. Met andere woorden, ik heb niks gewijzigd in de database(structuur), maar alleen de front-end aangepast. Zie https://test.shewrote.rich.ru.nl/sources/

**Comment by ACNMontoya** [comment]
Mooi, dank!
________________________________

**Comment by vanlummelhuizen** [comment]
Ook de Sources staan nu op de live-server. Ik sluit dit issue.
