### ISSUE TITLE
Add Language field to Work model

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#59]
Zie ook WomenWriters data.

**Comment by vanlummelhuizen** [comment]
@ACNMontoya 

Moet een Work meerdere Languages kunnen hebben? Dus dat de taal van een werk bijvoorbeeld zowel Frans als Nederland is, of het ene deel in het Frans is en het andere in het Nederlands. Of moet het maar een taal zijn?

Misschien is nog van belang dat een Edition al aan meerdere talen gelinkt kan worden.

**Comment by ACNMontoya** [comment]
Ja, een Work kan meerdere talen hebben. Een Edition heeft in principe dezelfde taal als het onderliggende Work (anders zou het een 'translation' zijn, wat weer een type Reception is).


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>




________________________________

**Comment by ACNMontoya** [comment]
Dank hiervoor. Het lijkt alleen wel alsof de WorkLanguages die in de oude versie van WomenWriters zaten niet zijn geimporteerd in SHEWROTE, klopt dat?

Bijvoorbeeld deze Work record in de oude versie: https://womenwriters.rich.ru.nl/womenwriters/vre/documents/fabed87f-c934-4d62-8a56-c0cb7784e6e3#prevnext=1

Maar in SHEWROTE lijkt de taal te ontrbeken (evenals Work genre): https://test.shewrote.rich.ru.nl/admin/shewrote/work/fabed87f-c934-4d62-8a56-c0cb7784e6e3/change/?_changelist_filters=q%3Djane#work-languages


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>




________________________________

**Comment by vanlummelhuizen** [comment]
> Het lijkt alleen wel alsof de WorkLanguages die in de oude versie van WomenWriters zaten niet zijn geimporteerd in SHEWROTE, klopt dat?

Ik heb nu alleen de functionaliteit toegevoegd. Ik was me er niet van bewust dat er ook data naar geimporteerd moest worden. Ik zal er naar kijken.

**Comment by vanlummelhuizen** [comment]
Ik heb mbv een script de WorkLanguages uit de original_data-velden van Works aangemaakt. Zie bv https://test.shewrote.rich.ru.nl/admin/shewrote/work/fabed87f-c934-4d62-8a56-c0cb7784e6e3/change/?_changelist_filters=q%3Djane#work-languages

Als het zo naar de live-server kan, dan hoor ik het graag.

**Comment by ACNMontoya** [comment]
Dit ziet er goed uit - alleen komt het geregeld voor wanneer ik nu op een Work klik dat ik een 'server error'  melding krijg, bijvoorbeeld https://test.shewrote.rich.ru.nl/works/d73f47e8-2754-4257-ad0b-011fc0208ea7/


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
> Dit ziet er goed uit - alleen komt het geregeld voor wanneer ik nu op een Work klik dat ik een 'server error' melding krijg, bijvoorbeeld https://test.shewrote.rich.ru.nl/works/d73f47e8-2754-4257-ad0b-011fc0208ea7/

Dat was een bug. Ik heb het opgelost. Kan het dan naar de live-server?

**Comment by ACNMontoya** [comment]
Dank, ja, het kan naar de live-server.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
@ACNMontoya Je hebt op 25 september de talen French en Dutch verwijderd. Heb je dat bewust gedaan? Zo ja, waarom? Zie ook https://shewrote.rich.ru.nl/admin/easyaudit/crudevent/?content_type__id__exact=17&event_type__exact=3

Het script waarmee ik Work en Language wilde koppelen gaf foutmeldingen dat deze twee talen niet bestonden.

**Comment by ACNMontoya** [comment]
Nee, dat heb ik niet bewust gedaan!


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>




________________________________

**Comment by vanlummelhuizen** [comment]
Gefixt. En de WorkLanguages zijn er nu ook. Ik sluit dit issue.
