### ISSUE TITLE
Show Editions in front end

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#61]
Lijst van Works met minstens Editions 

Op 1 regel:

* Author (Person)
* Work
* Datum
* Aantal Editions

=> details page: Lijst met Editions

**Comment by vanlummelhuizen** [comment]
@ACNMontoya Editions worden nu op de test-server getoond in de front-end zoals gevraagd. Ik hoor graag of het in orde is. Zie bv https://test.shewrote.rich.ru.nl/editions/ (er zijn nog geen Editions, dus om te zien hoe het werkt, moet je er eerst enkele aanmaken).

**Comment by vanlummelhuizen** [comment]
Gedaan. Zie https://test.shewrote.rich.ru.nl/work_edition/bb8c9434-dc06-4ecb-a568-3397e7c6f079/

**Comment by ACNMontoya** [comment]
Dank hiervoor. Ik vind het nu niet erg overzichtelijk om te lezen. Zou het mogelijk zijn de informatie in vijf kolommen te presenteren (met weglating van titel, die al bovenaan staat), zo:

[place] [publisher] [year] [notes] [URL]

Waarbij onder Notes alleen de eerste paar woorden staan, als er notes zijn, en onder URL niet het volledige adres hoeft te worden vermeld.

Verder geen vetgedrukte letters, en doorklikmogelijkheid naar de hele record bijvoorbeeld alleen bij de datum zetten.

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by ACNMontoya** [comment]
Prachtig, mooier kan niet.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Het staat op de live-server. Ik sluit dit issue.

**Comment by ACNMontoya** [comment]
Dank hiervoor, we zijn in onze nopjes hiermee.

Nu komen nog een heleboel nieuwe (lastige) vragen m.b.t. Editions.

Het is nu nog niet mogelijk om Persons toe te voegen aan een Edition. Dat zou mogelijk moeten worden. 'Language' (nu vermeld op de display pagina van Edition) mag vervallen.

Op de display pagina van een Edition zouden we graag ook de naam van de oorspronkelijke auteur willen zien.

En op de display pagina van Edition zou de vierde kolom eigen 'Re-editions' moeten heten (want elke Work heeft in principe al een Edition, dit zijn de herdrukken).

En - de echt lastige - onder Receptions zijn nu een heleboel Editions (met als reception type 'is edition of') ondergebracht die op den duur verplaatst zouden moeten worden naar Editions.

En als kers op de taart zouden we graag Editions willen kunnen ordenen zowel naar datum van oorspronkelijke publicatie als naar aantal, met ook filtermogelijkheid naar Author en naar aantal Editions.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________
