### ISSUE TITLE
On Person details page, only 4 out of 33 Reception types are shown. Why?

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#65]

**Comment by vanlummelhuizen** [comment]
Related to #58

**Comment by vanlummelhuizen** [comment]
@ACNMontoya De receptions die tot nu bij Person getoond werden waren eigenlijk Works waarbij de Person een bepaalde Role had. Het lijstje van rollen dat werd gebruikt om de receptions (eigenlijk Works) te tonen waren hardcoded, oftewel het lijstje stond in de code en niet in de database.

Ik heb nu een lijstje toegevoegd zodat je kan vergelijken. Het tweede lijstje bevat echte Receptions en worden getoond in volgende van datum (jaartal). 

Zie bv https://test.shewrote.rich.ru.nl/persons/9392bd37-5d3e-4d97-952b-71b696d36ef1/#v-pills-reception

**Comment by ACNMontoya** [comment]
Dank hiervoor. Dit is duidelijk, dan zou het fijn zijn om alleen de tweede lijstje te presenteren op de pagina. Wel is het zo dat we een nieuwe receptietype hebben toegevoegd die hierbij hoort, namelijk 'Visually depicted in' (= Receptions met als type 'is portrait of'). Kan die bij deze lijst worden gezet ?

En om verwaaring te voorkomen, kan in de front-end de kop  'Works that are receptions of Aphra Behn' worden veranderd in 'Works that are receptions of Aphra Behn, the Person (for receptions of her works, see under each individual Work)?
---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
> Dank hiervoor. Dit is duidelijk, dan zou het fijn zijn om alleen de tweede lijstje te presenteren op de pagina. Wel is het zo dat we een nieuwe receptietype hebben toegevoegd die hierbij hoort, namelijk 'Visually depicted in' (= Receptions met als type 'is portrait of'). Kan die bij deze lijst worden gezet ? 
>
> En om verwaaring te voorkomen, kan in de front-end de kop 'Works that are receptions of Aphra Behn' worden veranderd in 'Works that are receptions of Aphra Behn, the Person (for receptions of her works, see under each individual Work)?

Je wilt alleen het tweede lijstje, maar je wil wel de kop van de eerste lijst houden?

**Comment by ACNMontoya** [comment]
Nee, de kop van de eerste lijst mag weg.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by ACNMontoya** [comment]
Ik zie nu een nieuw probleem, denk ik. Doordat de 'reception type' hardcoded is, worden nieuw gemaakte Receptions niet getoond. Althans, ik heb zojuist een nieuwe Reception aangemaakt van een Person, *portrait de Philonide, maar hij wordt niet getoond bij de relevante Person pagina. Dit is de URL van de Reception in de Admin: https://shewrote.rich.ru.nl/admin/shewrote/reception/d85caa83-ca0e-43af-8db1-60852f96fc6b/change/?_changelist_filters=q%3Dphilon.
En dit is de Person pagina waarop deze Reception zichtbaar zou moeten zijn: https://shewrote.rich.ru.nl/persons/a6adb2d5-b6df-482d-adc2-3307426a5888/

---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
> Ik zie nu een nieuw probleem, denk ik. Doordat de 'reception type' hardcoded is, worden nieuw gemaakte Receptions niet getoond. Althans, ik heb zojuist een nieuwe Reception aangemaakt van een Person, *portrait de Philonide, maar hij wordt niet getoond bij de relevante Person pagina. Dit is de URL van de Reception in de Admin: https://shewrote.rich.ru.nl/admin/shewrote/reception/d85caa83-ca0e-43af-8db1-60852f96fc6b/change/?_changelist_filters=q%3Dphilon. En dit is de Person pagina waarop deze Reception zichtbaar zou moeten zijn: https://shewrote.rich.ru.nl/persons/a6adb2d5-b6df-482d-adc2-3307426a5888/

De wijzigingen die de reception bij een Person tonen, staan nog niet op de live server. Zoals je vroeg in https://github.com/tsg-humlab/shewrote/issues/65#issuecomment-2475970092 ga ik alleen het tweede lijstje tonen met als titel 'Works that are receptions of Aphra Behn, the Person (for receptions of her works, see under each individual Work)', waar Aphra Behn natuurlijk vervangen wordt door de betreffende naam.

**Comment by vanlummelhuizen** [comment]
De Receptions sectie van een Person zie er nu zo uit: https://test.shewrote.rich.ru.nl/persons/9392bd37-5d3e-4d97-952b-71b696d36ef1/#v-pills-reception

Overigens, technisch gezien zijn het geen Work objecten maar Reception objecten in de database, dus 'Works that are receptions' klopt eigenlijk niet.

**Comment by ACNMontoya** [comment]
Dit ziet er goed uit.

Je hebt gelijk, het beste zou zijn om de kop 'Works that are receptions of Aphra Behn' te herformuleren 'Receptions of Aphra Behn, the person'.

Verder zou het fijn zijn voor het overzicht om ook de naam van de auteur van elke Reception in de lijst op te nemen, kan dat?


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
> Je hebt gelijk, het beste zou zijn om de kop 'Works that are receptions of Aphra Behn' te herformuleren 'Receptions of Aphra Behn, the person'. 
> 
> Verder zou het fijn zijn voor het overzicht om ook de naam van de auteur van elke Reception in de lijst op te nemen, kan dat?

Beide gedaan. Is het zo in orde, oftewel, kan het naar de live-server?

**Comment by ACNMontoya** [comment]
Prachtig - ja, hij kan zo naar live.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Het staat op live. Ik sluit  dit issue.
