### ISSUE TITLE
Add Country/place of residence to Person filter

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#69]
Kan deze filtermogelijkheid nog voor de workshop worden gecreerd? We kunnen namelijk nu alleen filteren op 'Country/place of birth'  en 'Country/place of death', die bij veel Person records ontbreekt. Wel hebben bijna alle Person records een 'lived in' Country/place, d.w.z. een 'Country/place of residence'.

**Comment by vanlummelhuizen** [comment]
> Kan deze filtermogelijkheid nog voor de workshop worden gecreerd?

Refereer je naar een eerdere comment of ander issue? Of bedoel je gewoon wat je daarna schrijft?

**Comment by vanlummelhuizen** [comment]
@ACNMontoya Ik heb mijn invulling van dit issue nu op de test-server staan: https://test.shewrote.rich.ru.nl/persons/

**Comment by ACNMontoya** [comment]
Dank. Is het mogelijk te zoeken naar alle Persons met bijvoorbeeld 'France' als Country/place of birth en/of Country/place of birth,  d.w.z. alle resultaten bij elkaar ?


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Elk veld verkleint nu de resultaat-set. Dus als je France invult bij Country/Place of birth en bij Country/Place of death dan vindt de applicatie de mensen die geboren zijn in France EN gestorven zijn in France. 

Wil je dat ik dit verander naar OF: 'vind alle personen die geboren zijn in France OF gestorven zijn in France'? En moet Country/place of residence ook met OF worden meegenomen?

**Comment by vanlummelhuizen** [comment]
Gedaan. Als het naar de live-server kan, hoor ik het graag.

**Comment by ACNMontoya** [comment]
Fijn, dank!


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Het staat op de live-server. Ik sluit dit issue.
