### ISSUE TITLE
Add UUID id fields for Profession, Genre, Religion and Language

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#7]
Because Profession, Genre and Religion are wwkeywords in the old WomenWriters database and they have UUIDs there, it is probably wise to also use UUIDs in the new database.

See https://repository.womenwriters.rich.ru.nl/v2.1/domain/wwkeywords/autocomplete/profession, https://repository.womenwriters.rich.ru.nl/v2.1/domain/wwkeywords/autocomplete/genre and https://repository.womenwriters.rich.ru.nl/v2.1/domain/wwkeywords/autocomplete/religion. 

PS There are more keyword types but they are not (yet) in the schema of the new database:
* education
* financialSituation
* maritalStatus
* socialClass

**Comment by vanlummelhuizen** [comment]
Also add UUID field to Language. Perhaps more to come.

**Comment by vanlummelhuizen** [comment]
And perhaps change the field name 'genre' for Genre, 'language' for Language etc. to 'name' for these models so that you have `Genre.name` instead of `Genre.genre` etc.

**Comment by vanlummelhuizen** [comment]
O, and we probably should make the `name` field unique. Otherwise there could for instance be two Genres 'Novel' which makes no sense. This also goes for Role models by the way.

**Comment by dennis-bor** [comment]
> O, and we probably should make the `name` field unique. Otherwise there could for instance be two Genres 'Novel' which makes no sense. This also goes for Role models by the way.

It makes sense to also do this for Profession, Religion, and Language.

**Comment by vanlummelhuizen** [comment]
> It makes sense to also do this for Profession, Religion, and Language.

Yup

**Comment by dennis-bor** [comment]
Done and done.
