### ISSUE TITLE
Change Receptions list format

### ISSUE THREAD

**Issue by vanlummelhuizen** [tsg-humlab/shewrote#70]
> Omdat ik vermoed dat dit niet veel werk is (?), durf ik dit ook te vragen, als het mogelijk is, ook vóór onze workshop op 5 december.
> 
> Graag zou ik op de display pagina van Reception in de front-end de Receptions willen tonen op één rij volgens het format : Author of reception - title of reception (kan ingekort) - Place of reception - date - received Person - received Work (als die er is). Daarnaast zou het erg fijn zijn om de Receptions alvast te kunnen ordenen op datum.

_Originally posted by @ACNMontoya in https://github.com/tsg-humlab/shewrote/issues/22#issuecomment-2507695497_

**Comment by vanlummelhuizen** [comment]
Op https://test.shewrote.rich.ru.nl/receptions/ kan je nu sorteren op Title of Date of reception. De laatste wordt als standaard gebruikt.

Ook wordt de lijst getoond zoals gevraagd: 

> Author of reception - title of reception (kan ingekort) - Place of reception - date - received Person - received Work (als die er is).

Als dit naar de live-server kan, hoor ik het graag.

**Comment by ACNMontoya** [comment]
Mooi, dank. Kan ook de Person die gelinkd is aan de received Work (=author of Work) ook erbij (had ik eigenlijk ook onder Received Person gevat, hoewel het om een indirecte receptie gaat)?


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>



________________________________

**Comment by vanlummelhuizen** [comment]
Gedaan. Ik heb bij deze Persons zowel de WorkReception-type als de PersonWork-role weggelaten omdat het anders niet erg duidelijk was.

**Comment by ACNMontoya** [comment]
Heel fijn zo. Kunnen als laatste detail de namen van personen niet-cursief worden gezet, en de Receptions zonder datum (nu '0') aan het einde van de lijst worden gezet? Dat oogt wat netter dan meteen al die lege Receptions voor ogen te krijgen.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>




________________________________

**Comment by vanlummelhuizen** [comment]
De datum 0  is daadwerkelijk het cijfer 0 als datum. Hoe dat zo komt weet ik niet. Ik zou alle data met waarde 0 op niks kunnen zetten, dan staan ze vanzelf achteraan.

**Comment by ACNMontoya** [comment]
Dat zou fijn zijn, dank.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>




________________________________

**Comment by vanlummelhuizen** [comment]
Persons zijn niet langer cursief. En date_of_reception met waarde 0 heb ik veranderd naar niks.

Kan het zo naar de live-server?

**Comment by ACNMontoya** [comment]
Prachtig - ja, het kan zo naar live.


---

Prof. dr. Alicia C. Montoya | Professor of French literature | Radboud University | Department of Romance Languages | P.O. Box 9103 | 6500 HD Nijmegen | The Netherlands | Tel. +31 24 3612152  |  office: Erasmusplein 1, 5.12

Principal Investigator, NWO Vici project Civic Fictions: Modelling Book-Reader Interactions in the Age of Revolution, 1760-1830: Civic fictions<https://www.ru.nl/en/research/research-projects/civic-fictions>

Past ERC Consolidator project: MEDIATE (Measuring Enlightenment: Disseminating Ideas, Authors, and Texts in Europe, 1665 - 1830): MEDIATE database (ru.nl)<https://mediate-database.cls.ru.nl/accounts/login/?next=/dashboard/> and MEDIATE website<https://mediate18.nl/>

Co-chair, DARIAH-EU Women Writers in History Working Group: Women Writers in History | DARIAH<https://www.dariah.eu/activities/working-groups/women-writers-in-history/#:~:text=The%20Women%20Writers%20Route%20was,to%20focus%20specifically%20on%20women.> and SHEWROTE (ru.nl)<https://shewrote.rich.ru.nl/>




________________________________

**Comment by vanlummelhuizen** [comment]
Gedaan. Ik sluit dit issue.
